<?php

namespace Tests\Feature\Admin;

use App\Enums\BrandRole;
use App\Models\Brand;
use App\Models\Plan;
use App\Models\Subscription;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CreateClientAccountTest extends TestCase
{
    use RefreshDatabase;

    private function admin(): User
    {
        return User::factory()->create(['is_admin' => true]);
    }

    public function test_admin_creates_isolated_client_with_own_brand(): void
    {
        $this->actingAs($this->admin())
            ->post(route('admin.accounts.store'), [
                'name' => 'Cliente Novo',
                'email' => 'cliente@example.com',
                'brand_name' => 'Empresa do Cliente',
                'password' => 'senha-super-segura',
                'password_confirmation' => 'senha-super-segura',
                'subscription' => 'none',
            ])
            ->assertRedirect()
            ->assertSessionHas('success');

        $client = User::where('email', 'cliente@example.com')->firstOrFail();
        $this->assertFalse($client->is_admin);
        $this->assertNotNull($client->email_verified_at);

        // Tem exatamente UMA marca, como Owner, e é a marca ativa
        $this->assertSame(1, $client->brands()->count());
        $brand = $client->brands()->first();
        $this->assertSame('Empresa do Cliente', $brand->name);
        $this->assertSame(BrandRole::Owner, $client->roleInBrand($brand));
        $this->assertSame($brand->id, $client->current_brand_id);
    }

    public function test_created_client_is_not_linked_to_other_brands(): void
    {
        $existingBrand = Brand::factory()->create();

        $this->actingAs($this->admin())
            ->post(route('admin.accounts.store'), [
                'name' => 'Outro Cliente',
                'email' => 'outro@example.com',
                'brand_name' => 'Marca Isolada',
                'password' => 'senha-super-segura',
                'password_confirmation' => 'senha-super-segura',
                'subscription' => 'none',
            ]);

        $client = User::where('email', 'outro@example.com')->firstOrFail();
        $this->assertFalse($client->brands()->whereKey($existingBrand->id)->exists());
    }

    public function test_admin_can_create_client_with_trial(): void
    {
        $plan = Plan::factory()->create();

        $this->actingAs($this->admin())
            ->post(route('admin.accounts.store'), [
                'name' => 'Trial Cliente',
                'email' => 'trial-cliente@example.com',
                'brand_name' => 'Marca Trial',
                'subscription' => 'trial',
                'plan_id' => $plan->id,
                'trial_days' => 30,
            ]);

        $client = User::where('email', 'trial-cliente@example.com')->firstOrFail();
        $sub = $client->subscriptions()->first();
        $this->assertSame(Subscription::STATUS_TRIALING, $sub->status);
        $this->assertEqualsWithDelta(30, now()->diffInDays($sub->trial_ends_at), 1);
    }

    public function test_admin_can_create_client_with_courtesy_plan(): void
    {
        $plan = Plan::factory()->create();

        $this->actingAs($this->admin())
            ->post(route('admin.accounts.store'), [
                'name' => 'Cortesia',
                'email' => 'cortesia@example.com',
                'brand_name' => 'Marca Cortesia',
                'subscription' => 'plan',
                'plan_id' => $plan->id,
            ]);

        $sub = User::where('email', 'cortesia@example.com')->firstOrFail()->subscriptions()->first();
        $this->assertSame(Subscription::STATUS_ACTIVE, $sub->status);
        $this->assertTrue($sub->isValid());
    }

    public function test_password_is_optional_and_autogenerated(): void
    {
        $this->actingAs($this->admin())
            ->post(route('admin.accounts.store'), [
                'name' => 'Sem Senha',
                'email' => 'semsenha@example.com',
                'brand_name' => 'Marca X',
                'subscription' => 'none',
            ])
            ->assertSessionHas('success');

        $this->assertDatabaseHas('users', ['email' => 'semsenha@example.com']);
    }

    public function test_non_admin_cannot_create_accounts(): void
    {
        $user = User::factory()->create(['is_admin' => false]);

        $this->actingAs($user)
            ->post(route('admin.accounts.store'), [
                'name' => 'X',
                'email' => 'x@example.com',
                'brand_name' => 'Y',
                'subscription' => 'none',
            ])
            ->assertForbidden();
    }
}
